-- MySQL Script generated by MySQL Workbench
-- Wed May  1 22:28:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TableTipoConta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableTipoConta` (
  `idTipoConta` BIGINT NOT NULL,
  `tipo` VARCHAR(30) NULL,
  PRIMARY KEY (`idTipoConta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TableAgencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableAgencia` (
  `idAgencia` BIGINT NOT NULL,
  `codigo` INT NOT NULL,
  PRIMARY KEY (`idAgencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TableReserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableReserva` (
  `idReserva` BIGINT NOT NULL,
  `valor` DOUBLE NULL,
  PRIMARY KEY (`idReserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TableCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableCliente` (
  `idCliente` BIGINT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` INT NOT NULL,
  `telefone` INT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TableConta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableConta` (
  `idConta` BIGINT NOT NULL,
  `codigo` INT NOT NULL,
  `saldo` DOUBLE NULL,
  `TableTipoConta_idTipoConta` BIGINT NOT NULL,
  `Agencia_idAgencia` BIGINT NOT NULL,
  `TableReserva_idReserva` BIGINT NOT NULL,
  `TableCliente_idCliente` BIGINT NOT NULL,
  PRIMARY KEY (`idConta`, `TableTipoConta_idTipoConta`, `Agencia_idAgencia`, `TableReserva_idReserva`, `TableCliente_idCliente`),
  INDEX `fk_TableConta_TableTipoConta_idx` (`TableTipoConta_idTipoConta` ASC) VISIBLE,
  INDEX `fk_TableConta_Agencia1_idx` (`Agencia_idAgencia` ASC) VISIBLE,
  INDEX `fk_TableConta_TableReserva1_idx` (`TableReserva_idReserva` ASC) VISIBLE,
  INDEX `fk_TableConta_TableCliente1_idx` (`TableCliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_TableConta_TableTipoConta`
    FOREIGN KEY (`TableTipoConta_idTipoConta`)
    REFERENCES `mydb`.`TableTipoConta` (`idTipoConta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TableConta_Agencia1`
    FOREIGN KEY (`Agencia_idAgencia`)
    REFERENCES `mydb`.`TableAgencia` (`idAgencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TableConta_TableReserva1`
    FOREIGN KEY (`TableReserva_idReserva`)
    REFERENCES `mydb`.`TableReserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TableConta_TableCliente1`
    FOREIGN KEY (`TableCliente_idCliente`)
    REFERENCES `mydb`.`TableCliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TableCartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableCartao` (
  `idCartao` BIGINT NOT NULL,
  `numero` INT NOT NULL,
  `cvc` CHAR(5) NOT NULL,
  `validade` DATE NOT NULL,
  `TableConta_idConta` BIGINT NOT NULL,
  `TableConta_TableTipoConta_idTipoConta` BIGINT NOT NULL,
  `TableConta_Agencia_idAgencia` BIGINT NOT NULL,
  `TableConta_TableReserva_idReserva` BIGINT NOT NULL,
  `TableConta_TableCliente_idCliente` BIGINT NOT NULL,
  PRIMARY KEY (`idCartao`, `TableConta_idConta`, `TableConta_TableTipoConta_idTipoConta`, `TableConta_Agencia_idAgencia`, `TableConta_TableReserva_idReserva`, `TableConta_TableCliente_idCliente`),
  INDEX `fk_TableCartao_TableConta1_idx` (`TableConta_idConta` ASC, `TableConta_TableTipoConta_idTipoConta` ASC, `TableConta_Agencia_idAgencia` ASC, `TableConta_TableReserva_idReserva` ASC, `TableConta_TableCliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_TableCartao_TableConta1`
    FOREIGN KEY (`TableConta_idConta` , `TableConta_TableTipoConta_idTipoConta` , `TableConta_Agencia_idAgencia` , `TableConta_TableReserva_idReserva` , `TableConta_TableCliente_idCliente`)
    REFERENCES `mydb`.`TableConta` (`idConta` , `TableTipoConta_idTipoConta` , `Agencia_idAgencia` , `TableReserva_idReserva` , `TableCliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TableEndereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableEndereco` (
  `idEndereco` BIGINT NOT NULL,
  `numero` TINYINT(5) NULL,
  `complemento` VARCHAR(45) NULL,
  `cep` INT NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TableTransacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableTransacao` (
  `idTransacao` BIGINT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `tipo` VARCHAR(30) NOT NULL,
  `valor` DOUBLE NOT NULL,
  PRIMARY KEY (`idTransacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TablePix`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TablePix` (
  `idPix` BIGINT NOT NULL,
  `chave` INT NULL,
  `TableConta_idConta` BIGINT NOT NULL,
  `TableConta_TableTipoConta_idTipoConta` BIGINT NOT NULL,
  `TableConta_Agencia_idAgencia` BIGINT NOT NULL,
  `TableConta_TableReserva_idReserva` BIGINT NOT NULL,
  PRIMARY KEY (`idPix`, `TableConta_idConta`, `TableConta_TableTipoConta_idTipoConta`, `TableConta_Agencia_idAgencia`, `TableConta_TableReserva_idReserva`),
  INDEX `fk_TablePix_TableConta1_idx` (`TableConta_idConta` ASC, `TableConta_TableTipoConta_idTipoConta` ASC, `TableConta_Agencia_idAgencia` ASC, `TableConta_TableReserva_idReserva` ASC) VISIBLE,
  CONSTRAINT `fk_TablePix_TableConta1`
    FOREIGN KEY (`TableConta_idConta` , `TableConta_TableTipoConta_idTipoConta` , `TableConta_Agencia_idAgencia` , `TableConta_TableReserva_idReserva`)
    REFERENCES `mydb`.`TableConta` (`idConta` , `TableTipoConta_idTipoConta` , `Agencia_idAgencia` , `TableReserva_idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TableExtrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableExtrato` (
  `intExtrato` BIGINT NOT NULL,
  PRIMARY KEY (`intExtrato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TableConta_has_TableTransacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableConta_has_TableTransacao` (
  `TableConta_idConta` BIGINT NOT NULL,
  `TableConta_TableTipoConta_idTipoConta` BIGINT NOT NULL,
  `TableConta_Agencia_idAgencia` BIGINT NOT NULL,
  `TableConta_TableReserva_idReserva` BIGINT NOT NULL,
  `TableTransacao_idTransacao` BIGINT NOT NULL,
  PRIMARY KEY (`TableConta_idConta`, `TableConta_TableTipoConta_idTipoConta`, `TableConta_Agencia_idAgencia`, `TableConta_TableReserva_idReserva`, `TableTransacao_idTransacao`),
  INDEX `fk_TableConta_has_TableTransacao_TableTransacao1_idx` (`TableTransacao_idTransacao` ASC) VISIBLE,
  INDEX `fk_TableConta_has_TableTransacao_TableConta1_idx` (`TableConta_idConta` ASC, `TableConta_TableTipoConta_idTipoConta` ASC, `TableConta_Agencia_idAgencia` ASC, `TableConta_TableReserva_idReserva` ASC) VISIBLE,
  CONSTRAINT `fk_TableConta_has_TableTransacao_TableConta1`
    FOREIGN KEY (`TableConta_idConta` , `TableConta_TableTipoConta_idTipoConta` , `TableConta_Agencia_idAgencia` , `TableConta_TableReserva_idReserva`)
    REFERENCES `mydb`.`TableConta` (`idConta` , `TableTipoConta_idTipoConta` , `Agencia_idAgencia` , `TableReserva_idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TableConta_has_TableTransacao_TableTransacao1`
    FOREIGN KEY (`TableTransacao_idTransacao`)
    REFERENCES `mydb`.`TableTransacao` (`idTransacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TableCliente_has_TableEndereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableCliente_has_TableEndereco` (
  `TableCliente_idCliente` BIGINT NOT NULL,
  `TableEndereco_idEndereco` BIGINT NOT NULL,
  PRIMARY KEY (`TableCliente_idCliente`, `TableEndereco_idEndereco`),
  INDEX `fk_TableCliente_has_TableEndereco_TableEndereco1_idx` (`TableEndereco_idEndereco` ASC) VISIBLE,
  INDEX `fk_TableCliente_has_TableEndereco_TableCliente1_idx` (`TableCliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_TableCliente_has_TableEndereco_TableCliente1`
    FOREIGN KEY (`TableCliente_idCliente`)
    REFERENCES `mydb`.`TableCliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TableCliente_has_TableEndereco_TableEndereco1`
    FOREIGN KEY (`TableEndereco_idEndereco`)
    REFERENCES `mydb`.`TableEndereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TableConta_has_TableExtrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TableConta_has_TableExtrato` (
  `TableConta_idConta` BIGINT NOT NULL,
  `TableConta_TableTipoConta_idTipoConta` BIGINT NOT NULL,
  `TableConta_Agencia_idAgencia` BIGINT NOT NULL,
  `TableConta_TableReserva_idReserva` BIGINT NOT NULL,
  `TableConta_TableCliente_idCliente` BIGINT NOT NULL,
  `TableExtrato_intExtrato` BIGINT NOT NULL,
  PRIMARY KEY (`TableConta_idConta`, `TableConta_TableTipoConta_idTipoConta`, `TableConta_Agencia_idAgencia`, `TableConta_TableReserva_idReserva`, `TableConta_TableCliente_idCliente`, `TableExtrato_intExtrato`),
  INDEX `fk_TableConta_has_TableExtrato_TableExtrato1_idx` (`TableExtrato_intExtrato` ASC) VISIBLE,
  INDEX `fk_TableConta_has_TableExtrato_TableConta1_idx` (`TableConta_idConta` ASC, `TableConta_TableTipoConta_idTipoConta` ASC, `TableConta_Agencia_idAgencia` ASC, `TableConta_TableReserva_idReserva` ASC, `TableConta_TableCliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_TableConta_has_TableExtrato_TableConta1`
    FOREIGN KEY (`TableConta_idConta` , `TableConta_TableTipoConta_idTipoConta` , `TableConta_Agencia_idAgencia` , `TableConta_TableReserva_idReserva` , `TableConta_TableCliente_idCliente`)
    REFERENCES `mydb`.`TableConta` (`idConta` , `TableTipoConta_idTipoConta` , `Agencia_idAgencia` , `TableReserva_idReserva` , `TableCliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TableConta_has_TableExtrato_TableExtrato1`
    FOREIGN KEY (`TableExtrato_intExtrato`)
    REFERENCES `mydb`.`TableExtrato` (`intExtrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
